{% set name = "napari-nyxus" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolusAI/napari-nyxus/archive/v{{ version }}.tar.gz
  sha256: 61002dffb8f1c303821c76de6b7e5c20c75257cdea30781eccba90e951423c95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - versioneer
    - wheel
  run:
    - python >={{ python_min }}
    - filepattern >=2.0.0
    - imagecodecs
    - magicgui
    - matplotlib-base
    - napari
    - napari-skimage-regionprops >=0.10.1
    - napari-workflows
    - numpy
    - nyxus >=0.5.0
    - pandas
    - qtpy
    - superqt

test:
  imports:
    - napari_nyxus
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-nyxus
  summary: |
    Nyxus Napari is a Napari plugin for running feature calculations on image-segmentation image pairs,
    using the Nyxus application to compute features.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/PolusAI/napari-nyxus

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
